### ISSUE TITLE
Huge vulnerability -- needs immediate attention

### ISSUE THREAD

**Issue by adamreis** [kaitlinhuben/kaitlinhuben.github.io#1]
![Happy Birthday!](http://media.giphy.com/media/gw3JY2uqiaXKaQXS/giphy.gif)

**Comment by adamreis** [comment]
![Dogs](http://media.giphy.com/media/10BpiKtK7bx5xC/giphy.gif)

**Comment by kaitlinhuben** [comment]
![](http://i1232.photobucket.com/albums/ff364/MinaFlow/tumblr_lti6jmuyMH1qbixcf.gif)
